///////////////////////////////////////////////////////////////////////////////
// CallClassicC.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CallClassicC.h"
#include "MyCPP_VersionedVersion.h"

///////////////////////////////////////////////////////////////////////////////
// CCallClassicC
///////////////////////////////////////////////////////////////////////////////

// Simulated first-order heater plant (demo scaffolding, not customer code):
// steady state temperature = ambient + gain * heater power [%]
static const double PLANT_AMBIENT = 25.0;   // [degC]
static const double PLANT_GAIN    = 1.0;    // [degC per % heater power]
static const double PLANT_TAU     = 8.0;    // time constant [s]

// Defaults used when the module instance has no parameters configured
static const double DEFAULT_KP         = 8.0;
static const double DEFAULT_KI         = 0.5;
static const double DEFAULT_KD         = 0.0;
static const double DEFAULT_HIGH_LIMIT = 110.0; // [degC]

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CCallClassicC
BEGIN_INTERFACE_MAP(CCallClassicC)
	INTERFACE_ENTRY_ITCOMOBJECT()
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITComOnlineChange, ITComOnlineChange)
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CCallClassicC, VID_MyCPP_Versioned, CID_MyCPP_VersionedCCallClassicC)
IMPLEMENT_ITCOMOBJECT(CCallClassicC)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CCallClassicC)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CCallClassicC 
BEGIN_SETOBJPARA_MAP(CCallClassicC)
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_CallClassicCParameter, m_Parameter)
	SETOBJPARA_VALUE(PID_CallClassicCCounter, m_Counter)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CCallClassicC 
BEGIN_GETOBJPARA_MAP(CCallClassicC)
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_CallClassicCParameter, m_Parameter)
	GETOBJPARA_VALUE(PID_CallClassicCCounter, m_Counter)
///</AutoGeneratedContent>
	// manual entry: lets the next module version pull the live controller
	// state out of this instance during an online change
	GETOBJPARA_VALUE(PID_CallClassicCXferState, m_Ctrl)
END_GETOBJPARA_MAP()


///////////////////////////////////////////////////////////////////////////////
CCallClassicC::CCallClassicC()
	: m_Trace(m_TraceLevelMax, m_spSrv)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	m_Counter = 0;
	m_pInputs = NULL;
	m_pOutputs = NULL;
///</AutoGeneratedContent>
	memset(&m_Ctrl, 0, sizeof(m_Ctrl));
	m_Ctrl.plantTemp = PLANT_AMBIENT;
}

///////////////////////////////////////////////////////////////////////////////
CCallClassicC::~CCallClassicC() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CCallClassicC)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CCallClassicC::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// query TcCOM object server for ITcADI interface with own object id, 
	// which retrieves a reference to the TMC module instance handler
	m_spADI.SetOID(m_objId);
	hr = FAILED(hr) ? hr : m_spSrv->TcQuerySmartObjectInterface(m_spADI);

	// Fall back to sensible defaults if the instance has no gains configured
	if (m_Parameter.Kp == 0 && m_Parameter.Ki == 0 && m_Parameter.Kd == 0)
	{
		m_Parameter.Kp = DEFAULT_KP;
		m_Parameter.Ki = DEFAULT_KI;
		m_Parameter.Kd = DEFAULT_KD;
	}
	if (m_Parameter.TempHighLimit == 0)
	{
		m_Parameter.TempHighLimit = DEFAULT_HIGH_LIMIT;
	}

	// Initialize the legacy controller core (plain C calls)
	pid_init(&m_Ctrl.pid, m_Parameter.Kp, m_Parameter.Ki, m_Parameter.Kd, 0.0, 100.0);

	tseq_cfg_t seqCfg;
	seqCfg.in_band       = 1.0;    // "at temperature" within +/-1 degC
	seqCfg.out_band      = 3.0;    // fall back to RAMP beyond +/-3 degC
	seqCfg.in_band_ticks = 500;    // in band for 500 cycles before TRACK
	seqCfg.high_limit    = m_Parameter.TempHighLimit;
	seqCfg.trip_ticks    = 100;    // 100 cycles above limit trips FAULT
	seqCfg.reset_margin  = 10.0;   // must cool 10 degC below limit to reset
	tseq_init(&m_Ctrl.seq, &seqCfg);

	m_Ctrl.plantTemp = PLANT_AMBIENT;

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CCallClassicC::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;

	// Retrieve pointer to data areas via ITcADI interface from TMC module handler
///<AutoGeneratedContent id="DataAreaPointerInitialization">
	hr = FAILED(hr) ? hr : m_spADI->GetImagePtr(sizeof(CallClassicCInputs), 0, ADI_CallClassicCInputs, (PVOID*)(&m_pInputs));
	hr = FAILED(hr) ? hr : m_spADI->GetImagePtr(sizeof(CallClassicCOutputs), 0, ADI_CallClassicCOutputs, (PVOID*)(&m_pOutputs));
///</AutoGeneratedContent>

	// TODO: Add any additional initialization

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		SetObjStateOS();
	}

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CCallClassicC::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;

	// Release pointer to data areas via ITcADI interface from TMC module handler
///<AutoGeneratedContent id="DataAreaPointerRelease">
	safe_release_imgptr(m_spADI, m_pInputs);
	safe_release_imgptr(m_spADI, m_pOutputs);
///</AutoGeneratedContent>

	// TODO: Add any additional deinitialization

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CCallClassicC::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA_STR());

	m_spADI = NULL;

	// TODO: Add deinitialization code

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITComOnlineChange">
///////////////////////////////////////////////////////////////////////////////
// PrepareOnlineChange is called after this instance has been set to PREOP in non RT context. 
// Parameter ipOldObj refers to the currently active instance which is still in OP. 
// Retrieve parameter values that are not changed during OP via ipOldObj here.
// 
// Parameter pOldInfo refers to instance data which includes the libraryId and
// the module class id. This information can be used to implement switch from one 
// specific version to another.
HRESULT CCallClassicC::PrepareOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo)
{
	HRESULT hr = S_OK;

	ULONG nData = sizeof(m_Parameter);
	PVOID pData = &m_Parameter;
	ipOldObj->TcGetObjPara(PID_CallClassicCParameter, nData, pData);

	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// PerformOnlineChange is called after this instance has been set to SAFEOP in RT context.
// Parameter ipOldObj refers to old instance which is now in SAFEOP. 
// Allows to retrieve data after the last cyclic update of the old instance and
// before the first cyclic update of this instance.
HRESULT CCallClassicC::PerformOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo)
{
	HRESULT hr = S_OK;

	ULONG nData = sizeof(m_Counter);
	PVOID pData = &m_Counter;
	ipOldObj->TcGetObjPara(PID_CallClassicCCounter, nData, pData);

	// Take over the live legacy-controller state (PID integrator, state
	// machine incl. latched faults, simulated plant) so the process
	// continues seamlessly instead of cold-starting after the switchover.
	// Overwrites the defaults set up by SetObjStatePS.
	nData = sizeof(m_Ctrl);
	pData = &m_Ctrl;
	ipOldObj->TcGetObjPara(PID_CallClassicCXferState, nData, pData);

	return hr;
}
///</AutoGeneratedContent>


///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CCallClassicC::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// task cycle time -> seconds (the legacy code's "tick")
	ULONG cycleTimeNs = 0;
	double dt = 0.001;
	if (SUCCEEDED(ipTask->GetCycleTime(&cycleTimeNs)) && cycleTimeNs > 0)
	{
		dt = cycleTimeNs * 1e-9;
	}

	// ---- legacy C code, called unchanged --------------------------------
	tseq_state_t state = tseq_step(&m_Ctrl.seq,
		m_pInputs->Enable != 0, m_pInputs->FaultReset != 0,
		m_pInputs->SetpointTemp, m_Ctrl.plantTemp);

	double power = 0.0;
	if (tseq_heater_allowed(&m_Ctrl.seq))
	{
		power = pid_step(&m_Ctrl.pid, m_pInputs->SetpointTemp, m_Ctrl.plantTemp, dt);
	}
	else
	{
		pid_reset(&m_Ctrl.pid);
	}
	// ---------------------------------------------------------------------

	// simulated heater plant (first-order lag), stands in for the real I/O
	m_Ctrl.plantTemp += dt / PLANT_TAU * (PLANT_AMBIENT + PLANT_GAIN * power - m_Ctrl.plantTemp);

	m_pOutputs->ActualTemp  = m_Ctrl.plantTemp;
	m_pOutputs->HeaterPower = power;
	m_pOutputs->CtrlState   = (ULONG)state;
	m_pOutputs->AlarmFlags  = tseq_alarms(&m_Ctrl.seq);

	m_Counter++;

	return hr;
}
///</AutoGeneratedContent>

