///////////////////////////////////////////////////////////////////////////////
// CallClassicC.h
#pragma once

#include "MyCPP_VersionedInterfaces.h"

// Legacy embedded C code (customer core), compiled unchanged as plain C.
// The headers are pure C, so include them with C linkage:
extern "C" {
#include "legacy/legacy_pid.h"
#include "legacy/legacy_temp_seq.h"
}

// Live controller state, bundled so the whole block can be handed over
// during an online change (see PID_CallClassicCXferState). The layout must
// stay identical between module versions that exchange it.
typedef struct _CallClassicCXferState
{
	pid_ctx_t  pid;
	tseq_ctx_t seq;
	double     plantTemp;
} CallClassicCXferState;

class CCallClassicC
	: public ITComObject
///<AutoGeneratedContent id="InheritanceList">
	, public ITComOnlineChange
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()

	CCallClassicC();
	virtual	~CCallClassicC();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITComOnlineChange
	virtual HRESULT TCOMAPI PrepareOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);
	virtual HRESULT TCOMAPI PerformOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);

	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	CallClassicCParameter m_Parameter;
	ULONG m_Counter;
	CallClassicCInputs* m_pInputs;
	CallClassicCOutputs* m_pOutputs;
///</AutoGeneratedContent>

	ITcADIPtr m_spADI;

	// Legacy controller core (customer C code) + simulated plant: state
	// lives in context structs owned by the module, not in statics inside
	// the C files — that is what makes it transferable across online change
	CallClassicCXferState m_Ctrl;
};
