///////////////////////////////////////////////////////////////////////////////
// MyCPP_VersionedClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MyCPP_VersionedClassFactory.h"
#include "MyCPP_VersionedServices.h"
#include "MyCPP_VersionedVersion.h"
#include "CallClassicC.h"

BEGIN_CLASS_MAP(CMyCPP_VersionedClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_MyCPP_Versioned, CID_MyCPP_VersionedCCallClassicC, SRVNAME_MYCPP_VERSIONED "!CCallClassicC", CCallClassicC)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMyCPP_VersionedClassFactory::CMyCPP_VersionedClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_MYCPP_VERSIONED));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MyCPP_Versioned));
#endif //defined(TCDBG_UNIT_VERSION)
}

