///////////////////////////////////////////////////////////////////////////////
// MyCPP_VersionedServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MyCPP_Versioned = 0x3F000000;
#define SRVNAME_MYCPP_VERSIONED "MyCPP_Versioned"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MyCPP_VersionedCCallClassicC = {0x8e064b94,0xb1df,0x2e50,{0xb6,0x2e,0xfb,0xe2,0xcd,0xda,0xcb,0xab}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_CallClassicCInputs 0
#define ADI_CallClassicCOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_CallClassicCParameter = 0x00000001;
const PTCID PID_CallClassicCCounter = 0x00000002;
///</AutoGeneratedContent>

// Manually defined parameter id (intentionally not in the TMC): exposes the
// live legacy-controller state block for transfer during an online change
const PTCID PID_CallClassicCXferState = 0x00000100;

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _CallClassicCParameter
{
	double Kp;
	double Ki;
	double Kd;
	double TempHighLimit;
} CallClassicCParameter, *PCallClassicCParameter;

typedef struct _CallClassicCInputs
{
	double SetpointTemp;
	ULONG Enable;
	ULONG FaultReset;
} CallClassicCInputs, *PCallClassicCInputs;

typedef struct _CallClassicCOutputs
{
	double ActualTemp;
	double HeaterPower;
	ULONG CtrlState;
	ULONG AlarmFlags;
} CallClassicCOutputs, *PCallClassicCOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
