///////////////////////////////////////////////////////////////////////////////
// MyCPP_VersionedInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "MyCPP_VersionedServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
